// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDokkPIVd2-pd9XT4rHIJps6ZpRcqer4xM',
    appId: '1:171142678585:web:cc4d7e643f2ff38c3f65e8',
    messagingSenderId: '171142678585',
    projectId: 'medi-database-kobi',
    authDomain: 'medi-database-kobi.firebaseapp.com',
    storageBucket: 'medi-database-kobi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGGMK1Q-sFJRfWR1ij_872T_3F0SGzwY',
    appId: '1:171142678585:android:0afedaa5df4d8ef43f65e8',
    messagingSenderId: '171142678585',
    projectId: 'medi-database-kobi',
    storageBucket: 'medi-database-kobi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrs80W--6OyGvb-OTy-kyyhHaW8tj-6U',
    appId: '1:171142678585:ios:e9e6ef1b6b670fb33f65e8',
    messagingSenderId: '171142678585',
    projectId: 'medi-database-kobi',
    storageBucket: 'medi-database-kobi.firebasestorage.app',
    iosBundleId: 'com.example.kobiProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGrs80W--6OyGvb-OTy-kyyhHaW8tj-6U',
    appId: '1:171142678585:ios:e9e6ef1b6b670fb33f65e8',
    messagingSenderId: '171142678585',
    projectId: 'medi-database-kobi',
    storageBucket: 'medi-database-kobi.firebasestorage.app',
    iosBundleId: 'com.example.kobiProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDokkPIVd2-pd9XT4rHIJps6ZpRcqer4xM',
    appId: '1:171142678585:web:85fd9152cbcc73d93f65e8',
    messagingSenderId: '171142678585',
    projectId: 'medi-database-kobi',
    authDomain: 'medi-database-kobi.firebaseapp.com',
    storageBucket: 'medi-database-kobi.firebasestorage.app',
  );
}
